{VER
ver:2
}
{LIB
act:A
acc:pe
ori:I
mea:450.000
std:100.000
src:
.
nft:20
fea:
forceBOGunitigger=1
isNotRandom=0
doNotTrustHomopolymerRuns=0
doTrim_initialNone=0
doTrim_initialMerBased=1
doTrim_initialFlowBased=0
doTrim_initialQualityBased=0
doRemoveDuplicateReads=1
doTrim_finalLargestCovered=1
doTrim_finalEvidenceBased=0
doTrim_finalBestEdge=0
doRemoveSpurReads=1
doRemoveChimericReads=1
doCheckForSubReads=0
doConsensusCorrection=0
forceShortReadFormat=0
constantInsertSize=0
fastqQualityValues=sanger
fastqOrientation=innie
fastqMates=/home/478358/WORKING/G_turnbulli/reads/G14_ec_ind/G14_ec_ind.1.fastq.gz,/home/478358/WORKING/G_turnbulli/reads/G14_ec_ind/G14_ec_ind.2.fastq.gz
.
}
{VER
ver:1
}
