{VER
ver:2
}
{LIB
act:A
acc:se
ori:U
mea:0.000
std:0.000
src:
.
nft:20
fea:
forceBOGunitigger=1
isNotRandom=0
doNotTrustHomopolymerRuns=0
doTrim_initialNone=0
doTrim_initialMerBased=1
doTrim_initialFlowBased=0
doTrim_initialQualityBased=0
doRemoveDuplicateReads=1
doTrim_finalLargestCovered=1
doTrim_finalEvidenceBased=0
doTrim_finalBestEdge=0
doRemoveSpurReads=1
doRemoveChimericReads=1
doCheckForSubReads=0
doConsensusCorrection=0
forceShortReadFormat=0
constantInsertSize=0
fastqQualityValues=sanger
fastqOrientation=innie
fastqReads=/home/478358/WORKING/turn/3-merging/G14-ec-G4-filtered-k31-kgt15-pgt0.9/G14-ec-G4-filtered-k31-kgt15-pgt0.9.merged.fastq.gz
.
}
{VER
ver:1
}
